(define zero (lambda (f) (lambda (x) x)))
(define succ (lambda (n) (lambda (f) (lambda (x) (f ((n f) x))))))
(define plus-v1 (lambda (m) (lambda (n) (lambda (f) (lambda (x) ((m f) ((n f) x)))))))
(define plus-v2 (lambda (m) (lambda (n) ((m succ) n))))
(define mult-v1 (lambda (m) (lambda (n) ((m (plus n)) zero))))
(define mult-v2 (lambda (m) (lambda (n) (lambda (f) (m (n f))))))
(define exp (lambda (m) (lambda (n) (n m))))
(alias plus plus-v1)
(alias mult mult-v2)
(define one (succ zero))
(define two ((plus one) one))
(define three ((plus two) one))
(define prtnum (lambda (x) ((x add1) 0)))

(define T (lambda (x) (lambda (y) x)))
(define F (lambda (x) (lambda (y) y)))
(define land (lambda (x) (lambda (y) ((x y) F))))
(define lor (lambda (x) (lambda (y) ((x T) y))))
(define lnot (lambda (x) ((x F) T)))
(define prtbool (lambda (x) ((x 'T) 'F)))
